### ISSUE TITLE
Cannot use deliver_later

### ISSUE THREAD

**Issue by NguyenHoangTuanKiet** [khangvinhle/servicepack#9]
time_entry_patch.rb, line 36: cannot use deliver_later to sent an email

**Comment by lcmtam** [comment]
<strike>https://github.com/khangvinhle/servicepack/commit/84f74ba0fccff887d1ecd3039f19757cf6b77ffc</strike>
oops, this is the working one: https://github.com/khangvinhle/servicepack/commit/b8c881bf27642aabebf227b75f2ce2aa768b9646
